/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class CustomIterable implements System.Iterator<Object> {
    global Boolean hasNext() {
        return null;
    }
    global Object next() {
        return null;
    }
}
