/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ValueStreamMapProxy {
    global ValueStreamMapProxy() {

    }
    global void generateEvents(Id vsmId, Datetime startDate, Datetime endDate) {

    }
    global void generateEvents(List<Id> ids) {

    }
global class InvocableVariablesDTO {
    @InvocableVariable(label='field history tracking endDate' required=false)
    global Datetime endDate;
    @InvocableVariable(label='field history tracking startDate' required=false)
    global Datetime startDate;
    @InvocableVariable(label='Value Stream Map Id' required=true)
    global Id vsmId;
    global InvocableVariablesDTO() {

    }
}
}
