/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ValueStreamMapEventEraserBatch implements Database.Batchable<Id>, Database.Stateful {
    global ValueStreamMapEventEraserBatch(List<Id> workItemIds, List<Id> stageIds, List<Id> blockIds) {

    }
    global ValueStreamMapEventEraserBatch(List<Id> workItemIds, List<Id> stageIds, List<Id> blockIds, List<copadovsm__Value_Stream_Map__c> valueStreamMaps) {

    }
    global void execute(Database.BatchableContext bc, List<Id> scope) {

    }
    global void finish(Database.BatchableContext bc) {

    }
    global System.Iterable start(Database.BatchableContext bc) {
        return null;
    }
}
