/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ValueStreamMapWorkItemCollectorBatch implements Database.Batchable<SObject>, Database.Stateful {
    global ValueStreamMapWorkItemCollectorBatch(List<copadovsm__Value_Stream_Map__c> valueStreamMaps, Integer index, List<String> workItemIds) {

    }
    global ValueStreamMapWorkItemCollectorBatch(List<copadovsm__Value_Stream_Map__c> valueStreamMaps, Integer index, List<String> workItemIds, Boolean isRecalculate) {

    }
    global void execute(Database.BatchableContext bc, List<SObject> scope) {

    }
    global void finish(Database.BatchableContext bc) {

    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return null;
    }
}
